[package]
name = "tree-bitset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"
bit-set = "0.5"
roaring = "0.10"

[[bench]]
name = "cmp"
harness = false